### ISSUE TITLE
 slibc/src/inttypes/div.c

### ISSUE THREAD

**Issue by textbrowser** [maandree/slibc#1]
Division by zero?

**Comment by textbrowser** [comment]
slibc/src/stdlib/div.c also.

**Comment by maandree** [comment]
libc should not protect against explicit division by zero.
Additionally slibc will often assume that invalid input is not given.

**Comment by textbrowser** [comment]
Alright. Please include this information in the documentation pages.

**Comment by maandree** [comment]
Added to documentation.
