### ISSUE TITLE
int execveat(int dirfd, const char* path, char* const argv[], char* const envp[], int flags)

### ISSUE THREAD

**Issue by textbrowser** [maandree/slibc#3]
Memory allocated for pathname is lost to execve(). execve() is not aware of the origins of path. Perhaps `@param   path  The pathname of the file to execute.` should clarify that the function will eventually purge the contents of the path parameter, if that's possible.

Storing the results of `execve(pathname, argv, envp);` is probably easier.

**Comment by maandree** [comment]
`path` cannot be overriden because it must be `const` and its allocation probably too small for reusing.
I have fixed the memory leak.
