### ISSUE TITLE
 slibc/src/stdlib/relpath.c

### ISSUE THREAD

**Issue by textbrowser** [maandree/slibc#7]
Please see the comment.

```
  if (absref == NULL)
    {
      p = strlen(cwd);
      absref = malloc((p + 1) + sizeof(char)); // Addition or multiplication?
      if (absref == NULL)
    goto fail;
      memcpy(absref, cwd, p);
      absref[p] = '/';
      absref[p + 1] = '\0';
    }
  else
    strrchr(absref, '/')[1] = '\0';
```

**Comment by maandree** [comment]
Impressive that you found that! Is has not negative effect on the behaviour of the function, exception for the (ignorable) edge-case that 1 extra byte would cause the process to run out of memory.

**Comment by textbrowser** [comment]
OK, please also review `absref[p + 1]`. I did not comment on it because I was not sure of the previous operation.

**Comment by maandree** [comment]
Oh, it should have been `(p + 2) * sizeof(char)`. Now I see how you found it.

**Comment by textbrowser** [comment]
I reviewed all malloc() instances and noticed that only this one used addition. Then I looked at the index. :o)
